export const artworks = [
    {
      id: 1,
      title: "Sunset Over the Ocean",
      description: "A breathtaking view of the sunset casting vibrant colors over the ocean waves.",
      imageUrl: "https://i.pinimg.com/736x/54/67/3f/54673ffbb9be94bf0e69032514cac202.jpg",
      artist: "Emily Johnson",
      year: 2021,
      medium: "Oil on Canvas",
      dimensions: "24 x 36 inches",
    },
    {
      id: 2,
      title: "Abstract Geometry",
      description: "An abstract piece featuring geometric shapes and bold colors that evoke a sense of movement.",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7TucXwUp8BqcxrskmHkAYHNjbgajnmWDZipIb6EgZWatS6qnB-mEKJqV7XyLxqVl6ZrE&usqp=CAU",
      artist: "Michael Smith",
      year: 2020,
      medium: "Acrylic on Canvas",
      dimensions: "30 x 30 inches",
    },
    {
      id: 3,
      title: "Forest Serenity",
      description: "A tranquil painting capturing the beauty of a serene forest landscape in early morning light.",
      imageUrl: "https://i.etsystatic.com/41640873/r/il/9ee9fe/4747318664/il_570xN.4747318664_br78.jpg",
      artist: "Sarah Lee",
      year: 2019,
      medium: "Watercolor",
      dimensions: "18 x 24 inches",
    },
    {
      id: 4,
      title: "City Lights at Night",
      description: "A vibrant cityscape painting that showcases the dazzling lights of a bustling metropolis at night.",
      imageUrl: "https://example.com/images/city-lights-night.jpg",
      artist: "David Kim",
      year: 2022,
      medium: "Digital Art",
      dimensions: "40 x 20 inches",
    },
    {
      id: 5,
      title: "Whimsical Dreams",
      description: "A playful and colorful artwork that invites viewers into a world of imagination and dreams.",
      imageUrl: "https://example.com/images/whimsical-dreams.jpg",
      artist: "Laura Chen",
      year: 2023,
      medium: "Mixed Media",
      dimensions: "36 x 48 inches",
    },
    {
      id: 6,
      title: "The Great Wave",
      description: "An iconic piece that captures the power and beauty of ocean waves crashing against the shore.",
      imageUrl: "https://example.com/images/great-wave.jpg",
      artist: "Hokusai (Reproduction)",
      year: 1831, // Original artwork year
      medium: "Woodblock Print",
      dimensions: "10 x 15 inches (framed)",
    },
    {
      id: 7,
      title: "Rural Bliss",
      description: "A peaceful rural scene depicting a quaint farmhouse surrounded by lush green fields.",
      imageUrl: "https://example.com/images/rural-bliss.jpg",
      artist: "James Anderson",
      year: 2021,
      medium: "Pastel on Paper",
      dimensions: "22 x 28 inches",
    },
    {
      id: 8,
      title: "Cosmic Journey",
      description: "An imaginative representation of space travel, featuring planets, stars, and galaxies.",
      imageUrl: "https://example.com/images/cosmic-journey.jpg",
      artist: "Nina Patel",
      year: 2022,
      medium: "Digital Painting",
      dimensions: "32 x 40 inches",
    },
  ];
